# aliases: replace a command outright
alias ls   'eza --icons --group-directories-first'
alias ll   'eza -l --icons --group-directories-first --git'
alias la   'eza -la --icons --group-directories-first --git'
alias lt   'eza --tree --level=2 --icons'
alias cat  'bat --paging=never'
alias grep 'rg'
alias find 'fd'
alias ip   'ip -color=auto'
alias cp   'cp -iv'
alias mv   'mv -iv'
alias rm   'rm -Iv'
alias mkdir 'mkdir -pv'
alias df   'df -h'
alias du   'du -h'
alias ff   'fastfetch'
