# GENERATED by `theme` from themes/templates — edit the template, not this file.
# Theme: harbour — fzf colours (starship has its own palette in starship.toml)
set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border=sharp --color=bg+:#111a30,fg+:#e4e8f4,hl:#ff8c32,hl+:#ff8c32,pointer:#ff8c32,prompt:#3b5fe0,border:#1a2547,info:#5d6784,marker:#5fc98a'

# fish syntax colours (global scope shadows the universal defaults)
set -g fish_color_normal          e4e8f4
set -g fish_color_command         3b5fe0
set -g fish_color_keyword         ff8c32
set -g fish_color_param           e4e8f4
set -g fish_color_option          9aa3bd
set -g fish_color_quote           5fc98a
set -g fish_color_redirection     5ec4d6
set -g fish_color_end             ff8c32
set -g fish_color_operator        ff8c32
set -g fish_color_escape          f2c14e
set -g fish_color_comment         5d6784
set -g fish_color_error           f0566a
set -g fish_color_autosuggestion  5d6784
set -g fish_color_valid_path      --underline
set -g fish_color_cwd             3b5fe0
set -g fish_color_search_match    --background=111a30
set -g fish_color_selection       --background=111a30
set -g fish_color_cancel          f0566a
set -g fish_pager_color_prefix    ff8c32
set -g fish_pager_color_completion e4e8f4
set -g fish_pager_color_description 5d6784
set -g fish_pager_color_progress  9aa3bd
set -g fish_pager_color_selected_background --background=111a30
