# GENERATED by `theme` from themes/templates — edit the template, not this file.
# Theme: mono — fzf colours (starship has its own palette in starship.toml)
set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border=sharp --color=bg+:#101010,fg+:#f2f2f2,hl:#ffffff,hl+:#ffffff,pointer:#ffffff,prompt:#9c9c9c,border:#1c1c1c,info:#4e4e4e,marker:#3ddc84'

# fish syntax colours (global scope shadows the universal defaults)
set -g fish_color_normal          f2f2f2
set -g fish_color_command         9c9c9c
set -g fish_color_keyword         ffffff
set -g fish_color_param           f2f2f2
set -g fish_color_option          a6a6a6
set -g fish_color_quote           3ddc84
set -g fish_color_redirection     e6e6e6
set -g fish_color_end             ffffff
set -g fish_color_operator        ffffff
set -g fish_color_escape          f5c542
set -g fish_color_comment         4e4e4e
set -g fish_color_error           ff4d5e
set -g fish_color_autosuggestion  4e4e4e
set -g fish_color_valid_path      --underline
set -g fish_color_cwd             9c9c9c
set -g fish_color_search_match    --background=101010
set -g fish_color_selection       --background=101010
set -g fish_color_cancel          ff4d5e
set -g fish_pager_color_prefix    ffffff
set -g fish_pager_color_completion f2f2f2
set -g fish_pager_color_description 4e4e4e
set -g fish_pager_color_progress  a6a6a6
set -g fish_pager_color_selected_background --background=101010
