# GENERATED by `theme` from themes/templates — edit the template, not this file.
# Theme: harbour — fzf colours (starship has its own palette in starship.toml)
set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border=sharp --color=bg+:#111a30,fg+:#e4e8f4,hl:#ff8c32,hl+:#ff8c32,pointer:#ff8c32,prompt:#3b5fe0,border:#1a2547,info:#5d6784,marker:#5fc98a'
