-- GENERATED by `theme` — cursor for theme {{name}}.
-- Top-level hl.exec_cmd() re-runs on every config reload (the old `exec`), so `theme set` re-applies it.
hl.env("XCURSOR_THEME", "{{cursor}}")
hl.exec_cmd("hyprctl setcursor {{cursor}} 24")
