# GENERATED by `theme` from themes/templates — edit the template, not this file.
# Theme: {{name}} — fzf colours (starship has its own palette in starship.toml)
set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border=sharp --color=bg+:#{{surface}},fg+:#{{text}},hl:#{{accent}},hl+:#{{accent}},pointer:#{{accent}},prompt:#{{primary_bright}},border:#{{overlay}},info:#{{muted}},marker:#{{green}}'

# fish syntax colours (global scope shadows the universal defaults)
set -g fish_color_normal          {{text}}
set -g fish_color_command         {{primary_bright}}
set -g fish_color_keyword         {{accent}}
set -g fish_color_param           {{text}}
set -g fish_color_option          {{subtext}}
set -g fish_color_quote           {{green}}
set -g fish_color_redirection     {{cyan}}
set -g fish_color_end             {{accent}}
set -g fish_color_operator        {{accent}}
set -g fish_color_escape          {{yellow}}
set -g fish_color_comment         {{muted}}
set -g fish_color_error           {{red}}
set -g fish_color_autosuggestion  {{muted}}
set -g fish_color_valid_path      --underline
set -g fish_color_cwd             {{primary_bright}}
set -g fish_color_search_match    --background={{surface}}
set -g fish_color_selection       --background={{surface}}
set -g fish_color_cancel          {{red}}
set -g fish_pager_color_prefix    {{accent}}
set -g fish_pager_color_completion {{text}}
set -g fish_pager_color_description {{muted}}
set -g fish_pager_color_progress  {{subtext}}
set -g fish_pager_color_selected_background --background={{surface}}
