# GENERATED by `theme` from themes/templates — edit the template, not this file.
# Theme: {{name}} — fzf colours (starship has its own palette in starship.toml)
set -gx FZF_DEFAULT_OPTS '--height 40% --layout=reverse --border=sharp --color=bg+:#{{surface}},fg+:#{{text}},hl:#{{accent}},hl+:#{{accent}},pointer:#{{accent}},prompt:#{{primary_bright}},border:#{{overlay}},info:#{{muted}},marker:#{{green}}'
