-- ─────────────────────────────────────────────────────────────
--  Hyprland — entry point (Lua config, Hyprland ≥ 0.55)
--  Each concern lives in lua/<name>.lua. Hyprland runs every
--  require() in its own scope, so an error in one file only
--  breaks that file. Order matters only where noted.
--  API reference: /usr/share/hypr/stubs/hl.meta.lua
-- ─────────────────────────────────────────────────────────────
require("lua.monitors")
require("lua.env")
require("lua.cursor")       -- generated by `theme`
require("lua.input")
require("lua.look")         -- reads lua/colors (generated by `theme`)
require("lua.animations")
require("lua.rules")
require("lua.layers")
require("lua.autostart")
require("lua.binds")        -- last: if this errors, Hyprland's emergency binds kick in
