// GENERATED by `theme` from themes/templates — edit the template, not this file.
// Theme: {{name}}. Quickshell hot-reloads this file, so `theme set` recolours the shell live.
pragma Singleton
import QtQuick

QtObject {
    readonly property string name: "{{name}}"

    readonly property color base:          "#{{base}}"
    readonly property color mantle:        "#{{mantle}}"
    readonly property color surface:       "#{{surface}}"
    readonly property color overlay:       "#{{overlay}}"
    readonly property color primary:       "#{{primary}}"
    readonly property color primaryBright: "#{{primary_bright}}"
    readonly property color accent:        "#{{accent}}"
    readonly property color accentDim:     "#{{accent_dim}}"
    readonly property color text:          "#{{text}}"
    readonly property color subtext:       "#{{subtext}}"
    readonly property color muted:         "#{{muted}}"
    readonly property color red:           "#{{red}}"
    readonly property color green:         "#{{green}}"
    readonly property color yellow:        "#{{yellow}}"

    // glass: the panel/card backgrounds (Hyprland blurs behind the layer)
    readonly property color glassPanel: Qt.rgba(mantle.r, mantle.g, mantle.b, 0.74)
    readonly property color glassCard:  Qt.rgba(mantle.r, mantle.g, mantle.b, 0.78)

    readonly property string fontUi:      "Oxanium"
    readonly property string fontDisplay: "Quantico"
    readonly property string fontIcon:    "JetBrainsMono Nerd Font"
    readonly property int    fontSize:    13
}
