# exec-once runs once at launch; exec runs on every config reload.
exec-once = waybar
exec-once = swaync
exec-once = awww-daemon --no-cache
exec-once = sleep 1 && ~/.local/bin/wall set
exec-once = hypridle
exec-once = hyprsunset
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = easyeffects --gapplication-service
